### ISSUE TITLE
No client connected

### ISSUE THREAD

**Issue by Vligsu** [mariolukas/HydraPlay#103]
Moving further after https://github.com/mariolukas/HydraPlay/issues/102, the <HydraPlayIP>:8080 shows:
![image](https://user-images.githubusercontent.com/71543709/217371992-50de173f-8569-40cf-88f5-656e42dfcd31.png)
and no playback, browsing whatever is possible.

Some more errors from logs from `DEBUG - hydraplay.server.Executor.Snapcast Server`:

```
[Error] (Avahi) Failed to create client: Daemon not running
[Error] (PosixStream) Exception: end of file
[Error] (PosixStream) Exception: end of file
[Error] (ControlSessionTCP) Error while reading from control socket: Connection reset by peer
[Error] (ControlSessionTCP) Error in socket shutdown: Transport endpoint is not connected
[Error] (StreamSessionTCP) Error reading message header of length 0: Connection reset by peer
[Error] (StreamSessionTCP) Error in socket shutdown: Transport endpoint is not connected
```
I removed timestamps from logs to save some space.

Suspicious info-message in logs `DEBUG - hydraplay.server.Executor.Mopidy_0: file caching not enabled` and one more error when opening <HydraPlayIP>:8080/client: `404: Not Found`. 

I'm not sure if these are related to the errors above, but for the sake of completeness I mention them here.

These results are the same when running Docker-container with Portainer stack and command line `docker-compose up`.

So far works:
* connecting Snapclient (Windows 10) to HydraPlay (Docker < LXC < Proxmox)

@mariolukas and everyone else, do you know how to overcome these errors? A hint in which direction to look for solution?

**Comment by mariolukas** [comment]
Thank you for the investigation.

> and no playback, browsing whatever is possible.
All you need to do is connect a Snapcast client to the Hydraplay setup and a player will appear in the web frontend.

You can use the native Snapcast Client from the Snapcast project, or you can just run a Browser based client by opening a browser tab with 

`http://< your hydraplay ip>/client/`

Click on the play button on the top right corner and a player should appear in the ui.

> :8080/client: 404: Not Found.

You missed the slash at the end, change `.../client` to `.../client/` and it will work.

> [Error] (Avahi) Failed to create client: Daemon not running
> [Error] (PosixStream) Exception: end of file
> [Error] (PosixStream) Exception: end of file
> [Error] (ControlSessionTCP) Error while reading from control socket: Connection reset by peer
> [Error] (ControlSessionTCP) Error in socket shutdown: Transport endpoint is not connected
> [Error] (StreamSessionTCP) Error reading message header of length 0: Connection reset by peer
> [Error] (StreamSessionTCP) Error in socket shutdown: Transport endpoint is not connected

Some of the errors can be ignored. But i will have a look to fix those things.

**Comment by Vligsu** [comment]
Thank you for your reply!

`http://<HydraPlayIP>:8080/client/` works as expected. There my Win10 Snapclient is visible and another Snapclient instance can be added.

However, `http://<HydraPlayIP>:8080` still shows the message `No client connected` even with to Snapcast instances running.

> Some of the errors can be ignored. But i will have a look to fix those things.
I am going to launch HydraPlay on a Debian machine (real HW no Proxmox no LXC) and reproduce the steps there. Can you please tell me, which errors can be ignored so that I focus only on those relevant?

It is so far not clear whether these errors are related to `No client connected` or not, right?

Also do you need any other pieces of information such as logs or configs?

**Comment by mariolukas** [comment]
I guess the connection problem is related to a network issue like blocked ports etc.

**Comment by Vligsu** [comment]
A very accurate guess! Allowing access from `<HydraPlayIP>` to Snapclients and vice versa explicitly rendered Snapclients visible under `http://<HydraPlayIP>:8080`. A feature of my network equipment I guess. This concludes the actual issue of "No client connected".

However these error messages
```
[Error] (Avahi) Failed to create client: Daemon not running
[Error] (PosixStream) Exception: end of file
[Error] (PosixStream) Exception: end of file
[Error] (ControlSessionTCP) Error while reading from control socket: Connection reset by peer
[Error] (ControlSessionTCP) Error in socket shutdown: Transport endpoint is not connected
[Error] (StreamSessionTCP) Error reading message header of length 0: Connection reset by peer
[Error] (StreamSessionTCP) Error in socket shutdown: Transport endpoint is not connected
```
appear again in the logs, which means they do not have an impact on this specific issue.

**Comment by Vligsu** [comment]
@mariolukas again many thanks for your support and this wonderful peace of SW!
