### ISSUE TITLE
One more thing. You need to build HydraPlay before you place the files into `/home/pi/hydraplay`

### ISSUE THREAD

**Issue by trigor74** [mariolukas/HydraPlay#17]
One more thing. You need to build HydraPlay before you place the files into `/home/pi/hydraplay`

1. Install node on the pi or on your local machine
2. change to the HydraPlay Source folder.
3. Install dependencies with `npm install`
4. change the ip and ports in `environment.ts`
5. Build with ng build
6. the result will be in `target/build`
7. copy all files in `target/build`  to `/home/pi/hydraplay` on the pi
8. try to connect.

_Originally posted by @mariolukas in https://github.com/mariolukas/HydraPlay/issues/16#issuecomment-513122140_

**Comment by trigor74** [comment]
Hi.
I have gray empty page.
Where else, besides file environment.ts, should I make a change? I see that still in file ./src/app/services/snapcast.service.ts is specified IP 192.168.178.56

**Comment by Craftyalchemist** [comment]
@trigor74 
did you manage to get this up and running? And if so, what did you modify?

Thanks

**Comment by mariolukas** [comment]
The configuration is now done by runtime. There is a pre release on github which comes with a new configuration interface. The config files are loaded when the player initializes. You are able to do the configs in assets/config/config.production.json now.
