### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by zionsuperfly** [mariolukas/HydraPlay#22]
hello all,
For the moment i cannot get the build.
these steps i did:

I installed node.js
created a folder at /home/pi/hydraplay
In home/pi/hydraplay I ran git clone https://github.com/mariolukas/HydraPlay.git.
I then ran npm install in home/pi/hydraplay/HydraPlay/hydraplay
if i run npm install in home/pi/hydraplay/HydraPlay
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/hydraplay/HydraPlay/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/hydraplay/HydraPlay/package.json'
npm WARN HydraPlay No description
npm WARN HydraPlay No repository field.
npm WARN HydraPlay No README data
npm WARN HydraPlay No license field.

up to date in 0.582s
found 0 vulnerabilities

if i run in npm install in home/pi/hydraplay/HydraPlay/hydraplay,
it start to build something but with some warning, also no build file is visible

Installed to /home/pi/hydraplay/HydraPlay/hydraplay/node_modules/node-sass/vendor/linux-arm-79/binding.node
npm WARN @angular/platform-browser-dynamic@7.2.15 requires a peer of @angular/compiler@7.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@7.3.9 requires a peer of @angular/compiler-cli@>=5.0.0 <8.0.0 || ^7.0.0-beta.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@7.3.9 requires a peer of typescript@>=2.4.0 < 3.3 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.5.0 requires a peer of @angular/compiler@>=2.3.1 <8.0.0 || >7.0.0-beta <8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

added 75 packages from 62 contributors and audited 43725 packages in 694.879s

5 packages are looking for funding
run npm fund for details

found 6 vulnerabilities (1 low, 3 moderate, 2 high)
run npm audit fix to fix them, or npm audit for details

can somebody help me with this? what do i do wrong?

kind regards

**Comment by zionsuperfly** [comment]
i installed git, npm and nodjs by apt-get install

**Comment by zionsuperfly** [comment]
i think this error gives the problem:

root@raspberrypi:/home/pi/HydraPlay/hydraplay# sudo npm install

> node-sass@4.12.0 install /home/pi/HydraPlay/hydraplay/node_modules/@angular-devkit/build-angular/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/linux-arm-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/linux-arm-64_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.13.0 install /home/pi/HydraPlay/hydraplay/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.0/linux-arm-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.0/linux-arm-64_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> core-js@2.6.10 postinstall /home/pi/HydraPlay/hydraplay/node_modules/core-js
> node postinstall || echo "ignore"

^C

**Comment by MrTiptop** [comment]
Hello I am having issues compiling here... here is my log file... any ideas?

> node-sass@4.12.0 install /root/HydraPlay/hydraplay/node_modules/@angular-devkit/build-angular/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/linux-arm-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/linux-arm-64_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.13.0 install /root/HydraPlay/hydraplay/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.0/linux-arm-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.0/linux-arm-64_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.12.0 postinstall /root/HydraPlay/hydraplay/node_modules/@angular-devkit/build-angular/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /root/HydraPlay/hydraplay/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/root/HydraPlay/hydraplay/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.21.0 | linux | arm
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.16
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.21.0
gyp verb command install [ '10.21.0' ]
gyp verb install input version string "10.21.0"
gyp verb install installing version: 10.21.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.21.0
gyp verb build dir attempting to create "build" dir: /root/HydraPlay/hydraplay/node_modules/@angular-devkit/build-angular/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /root/HydraPlay/hydraplay/node_modules/@angular-devkit/build-angular/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /root/HydraPlay/hydraplay/node_modules/@angular-devkit/build-angular/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /root/HydraPlay/hydraplay/node_modules/@angular-devkit/build-angular/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /root/HydraPlay/hydraplay/node_modules/@angular-devkit/build-angular/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/root/HydraPlay/hydraplay/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/HydraPlay/hydraplay/node_modules/@angular-devkit/build-angular/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/HydraPlay/hydraplay/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/10.21.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/10.21.0',
gyp info spawn args   '-Dnode_gyp_dir=/root/HydraPlay/hydraplay/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/10.21.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/root/HydraPlay/hydraplay/node_modules/@angular-devkit/build-angular/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture arm
gyp verb node dev dir /root/.node-gyp/10.21.0
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/root/HydraPlay/hydraplay/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/root/HydraPlay/hydraplay/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/root/HydraPlay/hydraplay/node_modules/which/which.js:80:29)
gyp ERR! stack     at /root/HydraPlay/hydraplay/node_modules/which/which.js:89:16
gyp ERR! stack     at /root/HydraPlay/hydraplay/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /root/HydraPlay/hydraplay/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Linux 5.4.72-v7+
gyp ERR! command "/usr/bin/node" "/root/HydraPlay/hydraplay/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /root/HydraPlay/hydraplay/node_modules/@angular-devkit/build-angular/node_modules/node-sass
gyp ERR! node -v v10.21.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1

> node-sass@4.13.0 postinstall /root/HydraPlay/hydraplay/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /root/HydraPlay/hydraplay/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/root/HydraPlay/hydraplay/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.21.0 | linux | arm
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.16
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.21.0
gyp verb command install [ '10.21.0' ]
gyp verb install input version string "10.21.0"
gyp verb install installing version: 10.21.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.21.0
gyp verb build dir attempting to create "build" dir: /root/HydraPlay/hydraplay/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /root/HydraPlay/hydraplay/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /root/HydraPlay/hydraplay/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /root/HydraPlay/hydraplay/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /root/HydraPlay/hydraplay/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/root/HydraPlay/hydraplay/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/HydraPlay/hydraplay/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/HydraPlay/hydraplay/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/10.21.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/10.21.0',
gyp info spawn args   '-Dnode_gyp_dir=/root/HydraPlay/hydraplay/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/10.21.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/root/HydraPlay/hydraplay/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture arm
gyp verb node dev dir /root/.node-gyp/10.21.0
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/root/HydraPlay/hydraplay/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/root/HydraPlay/hydraplay/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/root/HydraPlay/hydraplay/node_modules/which/which.js:80:29)
gyp ERR! stack     at /root/HydraPlay/hydraplay/node_modules/which/which.js:89:16
gyp ERR! stack     at /root/HydraPlay/hydraplay/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /root/HydraPlay/hydraplay/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Linux 5.4.72-v7+
gyp ERR! command "/usr/bin/node" "/root/HydraPlay/hydraplay/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /root/HydraPlay/hydraplay/node_modules/node-sass
gyp ERR! node -v v10.21.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN @angular/cdk@7.3.7 requires a peer of @angular/core@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/cdk@7.3.7 requires a peer of @angular/common@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/flex-layout@7.0.0-beta.24 requires a peer of @angular/core@>=7.0.0-rc.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/flex-layout@7.0.0-beta.24 requires a peer of @angular/common@>=7.0.0-rc.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@7.2.15 requires a peer of @angular/core@7.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@7.2.15 requires a peer of @angular/platform-browser@7.2.15 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@7.3.9 requires a peer of @angular/compiler-cli@>=5.0.0 <8.0.0 || ^7.0.0-beta.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@7.3.9 requires a peer of typescript@>=2.4.0 < 3.3 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.5.0 requires a peer of @angular/compiler@>=2.3.1 <8.0.0 || >7.0.0-beta <8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.5.0 requires a peer of @angular/core@>=2.3.1 <8.0.0 || >7.0.0-beta <8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint@5.11.0 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@2.29.0 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev || >= 3.0.0-dev || >= 3.1.0-dev but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.12.0 (node_modules/@angular-devkit/build-angular/node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.12.0 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.13.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-23T10_01_52_967Z-debug.log

**Comment by MrTiptop** [comment]
ok so it seems i needed to do "apt-get install build-essential" to fix "gyp ERR! stack Error: not found: make"

**Comment by mariolukas** [comment]
The new version brings a complete refactoring. Build works again.
