### ISSUE TITLE
docker file solely for hydra play

### ISSUE THREAD

**Issue by sasgoose** [mariolukas/HydraPlay#24]
Hey, 

Awesome project!! I saw the same youtube video as you a while ago but has taken me a while to get to the point of actually implementing it and what you have done is incredible! 

I have an unRAID box where I am running a mopidy docker container and a snapcast container. I am in the process of scaling this up to more mopidy containers. 

I was wondering if you could help in getting a hydraPlay docker container setup? or do you think it would be better to run Hydraplay on an Nginx docker to serve to my browsers? it looks like the current docker files install mopidy and snapcast. I am very new to writing docker files so I am sorry if this is basic 

Cheers

**Comment by mariolukas** [comment]
The  new Mopidy code brings docker support.
