### ISSUE TITLE
Black Screen - TypeError: this.getExtraNgModuleProviders is not a function 

### ISSUE THREAD

**Issue by MrSliff** [mariolukas/HydraPlay#31]
Hello friend,

i already knew your project some years ago, when i started to build my multiroom setup. Unfortunately i couldnt get it runnuing due to lack of experience and documentation.

I wanted to give it a try again now, but i ran into a similar issue again. 

I could already install and compile your interface wothout errors (only warnings), but i still have a black screen. IPs and Ports of Mopidy and Snapserver instances are correct. 

When i load the page in my Browser i get a black screen again and the following error: 
TypeError: this.getExtraNgModuleProviders is not a function

After some research I fount a thread at stackoverflow where it says there may be an incompatibility with @angular/platform-browser-dynamic package. 

I tried to update all version dependencies in the package.json file, but when i try to compile it with "ng build" i get even more errors. 

Do you maybe have a hint, where i could start troubleshooting?

**Comment by mariolukas** [comment]
I think i need to update the whole code. I didn't work on it for a long time.

**Comment by mariolukas** [comment]
fixed within the current version

**Comment by MrSliff** [comment]
Cool, thanks. Will give it a try soon.
