### ISSUE TITLE
Volume slider not uniformly positioned when having multiple devices in one stream

### ISSUE THREAD

**Issue by zwometer** [mariolukas/HydraPlay#44]
It seems that the volume slider stays in the same line, unless the device name is too long. Then it breaks into the next line.
The screenshot should make it clear.

![image](https://user-images.githubusercontent.com/16819588/142697876-e62e0452-e8f1-4bc2-94f7-4fe98dcb29c6.png)

**Comment by mariolukas** [comment]
fixed
