### ISSUE TITLE
Add support for Spotify playlists

### ISSUE THREAD

**Issue by zwometer** [mariolukas/HydraPlay#45]
Spotify playlist integration

- search for a playlist
- show all owned playlists
- append playlist to current queue
- play
- play on shuffle

**Comment by mariolukas** [comment]
> Spotify playlist integration
> 

- [ ] search for a playlist
- [x]  show all owned playlists
- [x] append playlist to current queue
- [x]  play

Related to another issue #53 
- [ ] play on shuffle

**Comment by mariolukas** [comment]
![Bildschirmfoto 2021-12-22 um 18 12 18](https://user-images.githubusercontent.com/1033122/147130081-2e59c072-ec0d-4799-8eb6-2d369223471f.png)
![Bildschirmfoto 2021-12-22 um 18 11 57](https://user-images.githubusercontent.com/1033122/147130090-36c167df-4a9f-4afa-9127-1171f97d8830.png)

**Comment by mariolukas** [comment]
![Bildschirmfoto 2021-12-22 um 18 12 18](https://user-images.githubusercontent.com/1033122/147130184-e001651c-2652-45e2-8dd8-aedba4d9642b.png)

**Comment by mariolukas** [comment]
![Bildschirmfoto 2021-12-22 um 18 13 01](https://user-images.githubusercontent.com/1033122/147130236-c0acb638-4974-4352-9765-71b3df2ec891.png)

**Comment by mariolukas** [comment]
done
