### ISSUE TITLE
Filter search results

### ISSUE THREAD

**Issue by zwometer** [mariolukas/HydraPlay#47]
Implement functionality to filter search results:

- deselect certain sources. (e.g. deselect Spotify to exclude Spotify results)
- select certain sources (e.g. only select Spotify to only show Spotify results)
- change filter AFTER completing a search (1. enter search term, 2. hit enter, 3. wait for search results, 4. change filter to refine the results)
- filter for metadata like length, release date, artist, ... (if possible)

**Comment by mariolukas** [comment]
done #70 [fead1fb](https://github.com/mariolukas/HydraPlay/commit/fead1fb4b863f6687c73190dcc290f368f172229)
