### ISSUE TITLE
Let the user add and delete streaming channels.

### ISSUE THREAD

**Issue by zwometer** [mariolukas/HydraPlay#48]
As far as I understand, there is currently a fixed number of 2 streams.

Let the user create a new one or even better: dynamically create one, as soon as all streams are being listened to, so there is always a "spare" one, in case a device wants to change to a free channel.

As long as 2 or more streams are unoccupied, delete one.

**Comment by zwometer** [comment]
For now the user can change the fixed number of streams in the hydra.private.json config file.
The line is called `"instances": 2`
( 2 is the default value )

**Comment by mariolukas** [comment]
Should be configured in the hydraplay config file by now, as described in the comment before. 

> For now the user can change the fixed number of streams in the hydra.private.json config file.
> The line is called `"instances": 2`
> ( 2 is the default value )
