### ISSUE TITLE
Adding songs to an empty queue and hitting play does not start playing.

### ISSUE THREAD

**Issue by zwometer** [mariolukas/HydraPlay#49]
When a stream is not playing anything (e.g. at the very beginning after starting the whole system) I can add new songs to a queue by searching and then clicking on the plus on the right of the search results.
If I subsequently press the play button (in the main playback screen) nothing happens.
I would expect the music from the queue to start playing.

edit: the skip to next song and skip to previous buttons also do nothing in this state.

**Comment by mariolukas** [comment]
fixed
