### ISSUE TITLE
UI change: queue change more accessible; stream control more clear

### ISSUE THREAD

**Issue by zwometer** [mariolukas/HydraPlay#50]
The UI is simple (for now) but there is room for improvement.

From the main (playback-) screen there are 2 screens that a user can switch to:

1. stream/device control
2. queue/song search

In everyday use the queue/song search functionality is the one that is probably used more frequently, so it should be easily accessible. Currently the user has to hit a tiny button in the bottom right corner to get there. This needs to be more prominent and easier to click.

The stream/device control is opened by clicking on the currently playing song cover art. It's big and easy to click, but the user is not informed about where they have to click to get to the stream/device control screen.

The "back" button from both screens is tiny and hard to reach at the top right. (Also it is not instantly clear that this is the back button, as it is more of a downward facing arrow.)

I attached a UI mock-up that shows the user at first glance what the options are. Three buttons for the three sections with the current one highlighted. This is in no way meant to be perfect. Only to visualize, what I mean. Obviously the words could be replaced by icons, the buttons could be moved to the top of the screen, etc.
( I think, the words "Streams" and "Queue" are not THAT helpful to a new user but at least they instantly know that they have 3 options/pages to check out and they will always know, where they are and how to get back. No hidden information. )

![image](https://user-images.githubusercontent.com/16819588/142703392-878bfea2-a646-448a-a8fb-b4b903327dab.png)

**Comment by mariolukas** [comment]
Here a first draft
![Bildschirmfoto 2021-11-26 um 01 33 28](https://user-images.githubusercontent.com/1033122/143510576-9ef148c0-d960-4b5a-b0f7-196f0a1103b9.png)

**Comment by mariolukas** [comment]
fixed within 0f00a7141fc24c4835c1410cb0bb60f25fa86c5a
