### ISSUE TITLE
Add "repeat" and "shuffle" to the HydraPlay queue

### ISSUE THREAD

**Issue by zwometer** [mariolukas/HydraPlay#53]
Add buttons to control the way, the current queue is played:

- Repeat: once the end of the current queue is reached, jump to the top again
- Repeat (1 track): once the end of the current track is reached, start it again from the beginning
- Shuffle: play the current queue in random order (without changing the actual order of the tracks in the queue)
- Shuffle Repeat: don't just play every track once in a random order, but continue playing them multiple times (in random order)

**Comment by mariolukas** [comment]
![Bildschirmfoto 2021-12-22 um 18 09 29](https://user-images.githubusercontent.com/1033122/147129853-5fe3be82-106c-402a-81c5-c58d7fdb4e2e.png)
 
Just some blueprints :)

**Comment by mariolukas** [comment]
done
