### ISSUE TITLE
Option to manually remove (inactive) Snapclient from list.

### ISSUE THREAD

**Issue by zwometer** [mariolukas/HydraPlay#57]
When a Snapclient goes offline it remains in the HydraPlay front-end. (at least for some time?)

It would be nice to have a button to manually remove a disconnected Snapclient.
I was able to achieve remove the disconnected client from the list by removing it on one of the other connected Snapclients but it feels like a dirty workaround...

**Comment by mariolukas** [comment]
closed by #59
