### ISSUE TITLE
Player still shows a "current song" after removing all tracks from queue.

### ISSUE THREAD

**Issue by zwometer** [mariolukas/HydraPlay#58]
How to reproduce:
1. Have a stream
2. Add a song to the tracklist
3. Start playing the song
4. The player now shows the cover art of the currently played (or paused) song.
5. Remove all songs from the tracklist

Expected behavior:
- The player now shows the "empty stream" placeholder image.

Actual behavior:
- The player still shows the cover art from step 4 above

Workaround:
- Reload HydraPlay Website removes the cover art and shows empty stream placeholder.

**Comment by mariolukas** [comment]
fixed within https://github.com/mariolukas/HydraPlay/commit/973f50d9d93530882526cddebc1b28fc85df17bd
