### ISSUE TITLE
The words "Player", "Streams", "Playlists", "Search", and "Tune" at the bottom are not clickable.

### ISSUE THREAD

**Issue by zwometer** [mariolukas/HydraPlay#60]
The words below the icons at the bottom of the panels are not clickable.
Obviously a very small issue. Maybe this even is intentional.
Especially using it on PC I intuitively tried clicking the words multiple times and nothing happened.

To me it feels like the icons combined with the text together represent a button/area that is clickable, but as of now only the icon is clickable.

**Comment by mariolukas** [comment]
fixed by #61

**Comment by zwometer** [comment]
tested. works well. Thanks for the quick fix!
