### ISSUE TITLE
Playlists and Tracklists not showing until user changes stream at least once.

### ISSUE THREAD

**Issue by zwometer** [mariolukas/HydraPlay#63]
**How to reproduce:**

1. Reload the HydraPlay-Website in Browser (I'm using Chrome on PC)
2. Click on "Playlists" on the bottom of any of the shown panels. An empty Tracklist is shown. Even if there are currently songs playing on this device/stream.
3. Click on "Playlists" on top. (next to "Tracklist"). An empty list of Playlists is shown.

**Current workaround: Change any stream:**

1. Click on "Streams" on the bottom of any of the shown panels.
2. Click any of the shown streams. Now the problem described above is fixed.

**Comment by mariolukas** [comment]
fixed
