### ISSUE TITLE
Error when I start Hydraplay with docker-compose on a Raspberry Pi

### ISSUE THREAD

**Issue by Medel** [mariolukas/HydraPlay#65]
I get an error after "docker-compose up"
ERROR: for hydraplay  Cannot start service hydraplay: driver failed programming external connectivity on endpoint hydraplay (c97335517f80432630950e211997aa76b0ed89a42d3a01974f1215e6a2178753): Error starting userland proxy: listen tcp4 0.0.0.0:6665: bind: address already in use

How can I change the port 6665?

**Comment by mariolukas** [comment]
Looks like you are already running a service on port 6665?

**Comment by Medel** [comment]
Yes the port is used by another program. How can I change the port

**Comment by mariolukas** [comment]
Just shift the ports in the lines behind the range of your used port: 

https://github.com/mariolukas/HydraPlay/blob/master/hydra.example.json#L6
and 
https://github.com/mariolukas/HydraPlay/blob/master/hydra.example.json#L7

Then adjust the ranges of the ports in docker compose to match the shifted ports

https://github.com/mariolukas/HydraPlay/blob/master/docker-compose.yml#L18
and
https://github.com/mariolukas/HydraPlay/blob/master/docker-compose.yml#L19

I think that will do the trick.

In your case i would suggest to use a base port 6666
and in compose file something like 6665-6679
You can also adjust the range. It depends on the number of mopidy instances in the 
config.

Lets say you have 2 instances in your config, what will provide two streams in the
player, you can change the range to 6665-6667 but it is always a good choice to
have some spare ports for quick adjustment of the instances.
In a normal use case you will have as many instances as you have clients connected
to the setup.

**Comment by Medel** [comment]
I changed the ports, build it again but there are other errors, see attached file
[log.txt](https://github.com/mariolukas/HydraPlay/files/8052053/log.txt)

**Comment by mariolukas** [comment]
Try to pull the latest version (from yesterday) i recently replaced the fifos by tcp streams.

**Comment by Medel** [comment]
For Raspberry Pi I also have to change Platform to linux/arm/v7 in docker-compose.yml. Is this correct?

**Comment by mariolukas** [comment]
The Raspberry Pi build is still work in progress. Are you able to run it on non-arm based systems?

**Comment by Medel** [comment]
I have also changed dockerfile to Dockerfile.armhf. Same output. 
Is it possible to use hydraplay without docker. I could install multiple Mopidy instances manually.

**Comment by mariolukas** [comment]
Is the Pi the only device you have tested?

**Comment by mariolukas** [comment]
Would a ready to use Raspberry Pi image be an option?

**Comment by Medel** [comment]
No there are more programs running

**Comment by mariolukas** [comment]
Ok. But i think the issue will remain. It seems that the this line causes the error

https://github.com/mariolukas/HydraPlay/blob/master/src/hydraplay/server/MopidyPoolService.py#L21

I will try to reproduce the error on one of my Pis.

**Comment by mariolukas** [comment]
I just changed some stuff. Fixed the "fifo error". You should do the follwing: 

1. Pull the updated code
2. Stop and Remove all hydraplay docker containers

`docker stop hydraplay && docker rm hydraplay`

2. Remove the old Docker images (its better to start with a clean build)

`docker rmi $(docker images -q hydraplay_hydraplay)`

3. Be sure your hydraplay and docker config is correct. Change your ports as described above to both files. Then set dockerfile in build section of docker-compose file to Dockerfile.armhf

4. Build the docker image
`docker-compose build`

5. Run it ( add -d for daemon if required)
`docker-compose up`

6. Connect a snapclient to the setup by running
`snapclient -h <ip of your server host system>`
Or use the Android Client for Mobile Devices.
 
7. Open a Browser with

http://<ip of your server host>:8080

( you can also change this port in the hydraplay.cofig.json file)

I hope this works. I did the changes in the code and tested it afterwards on a Raspberry pi. It works for me. 
Just one small visual issue with the ui when the player is started for the first time, but i will fix it soon.

**Comment by Medel** [comment]
docker-compose build - OK
docker-compose up - OK no Error, only info and debug
But only a black screen in the browser
Here is the output after connecting (two clients tested)
```
hydraplay    | 2022-02-12 16:28:26,594 [11:1995564864] INFO - tornado.access: 200 GET / (192.168.1.202) 5.90ms
hydraplay    | 2022-02-12 16:28:26,661 [11:1995564864] INFO - tornado.access: 304 GET /runtime.js (192.168.1.202) 5.17ms
hydraplay    | 2022-02-12 16:28:26,673 [11:1995564864] INFO - tornado.access: 304 GET /polyfills.js (192.168.1.202) 4.69ms
hydraplay    | 2022-02-12 16:28:26,685 [11:1995564864] INFO - tornado.access: 304 GET /scripts.js (192.168.1.202) 5.08ms
hydraplay    | 2022-02-12 16:28:26,700 [11:1995564864] INFO - tornado.access: 200 GET /styles.css (192.168.1.202) 9.59ms
hydraplay    | 2022-02-12 16:28:26,715 [11:1995564864] INFO - tornado.access: 304 GET /main.js (192.168.1.202) 4.46ms
hydraplay    | 2022-02-12 16:28:27,008 [11:1995564864] INFO - tornado.access: 200 GET /api/mopidy/settings (192.168.1.202) 3.82ms
hydraplay    | 2022-02-12 16:28:27,072 [11:1995564864] INFO - tornado.access: 200 GET /favicon.ico (192.168.1.202) 5.01ms
hydraplay    | 2022-02-12 16:28:27,119 [11:1949299808] DEBUG - hydraplay.server.Executor.Snapcast Server: 2022-02-12 16-28-27.118 [Notice] (ControlServer) ControlServer::NewConnection: 192.168.1.202
hydraplay    | 2022-02-12 16:28:27,120 [11:1949299808] DEBUG - hydraplay.server.Executor.Snapcast Server: 2022-02-12 16-28-27.119 [Info] (ControlServer) Removing 2 inactive session(s), active sessions: 2
hydraplay    | 2022-02-12 16:28:56,393 [11:1995564864] INFO - tornado.access: 304 GET / (192.168.1.42) 6.24ms
hydraplay    | 2022-02-12 16:28:56,450 [11:1995564864] INFO - tornado.access: 304 GET /runtime.js (192.168.1.42) 4.25ms
hydraplay    | 2022-02-12 16:28:56,464 [11:1995564864] INFO - tornado.access: 304 GET /polyfills.js (192.168.1.42) 4.11ms
hydraplay    | 2022-02-12 16:28:56,474 [11:1995564864] INFO - tornado.access: 304 GET /main.js (192.168.1.42) 4.07ms
hydraplay    | 2022-02-12 16:28:56,487 [11:1995564864] INFO - tornado.access: 304 GET /scripts.js (192.168.1.42) 4.13ms
hydraplay    | 2022-02-12 16:28:56,736 [11:1995564864] INFO - tornado.access: 304 GET /styles.css (192.168.1.42) 5.55ms
hydraplay    | 2022-02-12 16:28:56,894 [11:1995564864] INFO - tornado.access: 304 GET /api/mopidy/settings (192.168.1.42) 3.78ms
hydraplay    | 2022-02-12 16:28:56,984 [11:1949299808] DEBUG - hydraplay.server.Executor.Snapcast Server: 2022-02-12 16-28-56.983 [Notice] (ControlServer) ControlServer::NewConnection: 192.168.1.42
hydraplay    | 2022-02-12 16:28:56,985 [11:1949299808] DEBUG - hydraplay.server.Executor.Snapcast Server: 2022-02-12 16-28-56.984 [Info] (ControlServer) Removing 2 inactive session(s), active sessions: 2
```

**Comment by mariolukas** [comment]
A black screen means that no client is connected to the server. 
You need to run a client on the same system or on another one.
The client needs to be started with -h for host followed by the
ip of the server.

**Comment by mariolukas** [comment]
Which version of the client are you using?

**Comment by mariolukas** [comment]
Can you provide more logs, especially form the startup sequence.

**Comment by Medel** [comment]
With a connected Android client it is showing. I guess it is not the opus codec. My ESP32 is showing but not playing. Is there a way to change the codec.

**Comment by mariolukas** [comment]
I've never used an ESP32 client. The interesting question is if the codec needs to be changed in mopidy or snapcast. I guess it needs to be changed in mopidy. Maybe the magic line is: 

https://github.com/mariolukas/HydraPlay/blob/master/src/hydraplay/config/templates/mopidy.conf.j2#L21
and/or
https://github.com/mariolukas/HydraPlay/blob/master/src/hydraplay/config/templates/mopidy.conf.j2#L18

depending on the pipe (fifo/tcp).

**Comment by mariolukas** [comment]
I think this can be closed and the ESP32 related stuff should be moved to an new issue.
