### ISSUE TITLE
Select codec for the Snapcast Server in hydra.private.json

### ISSUE THREAD

**Issue by Medel** [mariolukas/HydraPlay#67]
I use an ESP32 as Snapcast client, but it has only the opus codec.

**Comment by mariolukas** [comment]
Can you try to get it running by changing 

https://github.com/mariolukas/HydraPlay/blob/master/src/hydraplay/config/templates/mopidy.conf.j2#L21
and/or
https://github.com/mariolukas/HydraPlay/blob/master/src/hydraplay/config/templates/mopidy.conf.j2#L18

Maybe it would work with:

`output = audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! opusdec ! tcpclientsink host=127.0.0.1 port={{ tcp_port |int + stream_id |int }}`

Can you give this a try?

**Comment by mariolukas** [comment]
Ok fine. Can you prove if it works when you use it here
https://github.com/mariolukas/HydraPlay/blob/master/src/hydraplay/config/templates/snapserver.conf.j2#L89

**Comment by Medel** [comment]
Your first recommendation does not work 
`output = audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! opusenc ! tcpclientsink host=127.0.0.1 port={{ tcp_port |int + stream_id |int }}
`

But the second one works

**Comment by mariolukas** [comment]
https://github.com/mariolukas/HydraPlay/blob/master/hydra.example.json#L36
