### ISSUE TITLE
 Scrollbar not visible in search view (content overflow issue)

### ISSUE THREAD

**Issue by Medel** [mariolukas/HydraPlay#69]
There is no scrollbar in the window. See screenshut
![Screenshot](https://user-images.githubusercontent.com/3252272/153746424-16292a2b-0da9-4ca1-a83c-aaafaf838bfd.jpg)

**Comment by mariolukas** [comment]
Can you provide more information about: 
- resolution of the used device
- browser and version
- mobile or desktop

**Comment by Medel** [comment]
OS: Linux Opensuse 15.3
Browser: Firefox 91.5.0esr (64-Bit) wrong without scrollbar
Browser: Chromium Version 98.0.4758.80 (openSUSE Build) stable (64-Bit) is ok with scrollbar
Browser: Konqueror Version 5.0.97 is ok with scrollbar

Android 11 Tablet S5e:
Browser: Firefox Version 97.1.0 wrong without scrollbar
Browser: Chrom 98.0.4758.87 ok with scrollbar

**Comment by mariolukas** [comment]
Thanks for the detailed report.
