### ISSUE TITLE
N SnapCast instances

### ISSUE THREAD

**Issue by LeoSum8** [mariolukas/HydraPlay#7]
Hi @mariolukas, I just found your repo here.
Nice work! I had also seen that youtube video you mention in the readme and found the interface quite nice.

I am looking to integrate your Interface into my setup and am currently trying to understand how it is working and what I would have to change.

I think there is a copy-paste-mistake in your Readme.

Did you mean `N mopidy instances` where you write `N SnapCast instances`?

```
Software on Server:
- Pulseaudio
- Snapcast Server
- N SnapCast instances
- SnapProxy
```

**Comment by mariolukas** [comment]
You are right, it should be N Mopidy instances. 
I will fix it.

**Comment by mariolukas** [comment]
I am writing a blog post about the basic setup, and i am working on an installation guide. 
The project is really fresh. Started it a week ago.
