### ISSUE TITLE
Add support for mopidy extentions

### ISSUE THREAD

**Issue by Loigzorn** [mariolukas/HydraPlay#72]
Request to add more [mopidy extentions](https://mopidy.com/ext/) that are already supported by mopidy but not jet by hydraplay.

In my case I wanted to add the [bandcamp extention](https://mopidy.com/ext/bandcamp/) but in the logs I found this line:

> DEBUG - hydraplay.server.Executor.Mopidy_1: Ignoring config section 'bandcamp' because no matching extension was found

**Comment by mariolukas** [comment]
done within 0.6.1 https://github.com/mariolukas/HydraPlay/blob/master/hydra.example.json#L34
