### ISSUE TITLE
Player directory/files missing in git

### ISSUE THREAD

**Issue by Medel** [mariolukas/HydraPlay#74]
There is no directory for the player in git.
HydraPlay/src/hydraplay/server/static/player is missing

**Comment by mariolukas** [comment]
It is because it will be created during the build process of the frontend code. 
https://github.com/mariolukas/HydraPlay/blob/master/src/ui/angular.json#L23

**Comment by Medel** [comment]
I do not use docker, I install it locally. I just see the build steps for the UI and started it. "Npm install" takes a long time. I'll try "ng build" if it is finish.

**Comment by Medel** [comment]
Building on a Raspberry is not practical, NPM Install takes over 20 minutes 394MB, 873 Install size, ng build runs already since 20 minutes "phase setup", I guess there is not enough memory.

**Comment by mariolukas** [comment]
Ok sounds reasonable to me. Maybe it makes sense to add a package with the pre-built player as built artefact beside each released tag.

**Comment by mariolukas** [comment]
There are release files now (https://github.com/mariolukas/HydraPlay/releases/tag/0.7.4) Those zip files contain all pre-built components.

**Comment by mariolukas** [comment]
Just added an install.sh script 
https://github.com/mariolukas/HydraPlay/blob/master/install.sh
