### ISSUE TITLE
Some questions there

### ISSUE THREAD

**Issue by beber666** [mariolukas/HydraPlay#78]
Hi

I'm coming following some advices received on Reddit.
Seems Hydraplay will solve my problems :-)

Here is my house configuration:
- 1 or 2 speakers per Room (Around 4 rooms)
- I would like, if possible, to stream directly from my phone Spotify App
- ...And if possible use only one Raspberry with multiple soundcards
- Also, if possible, have Airplay

Of what I understood, Hydraplay will launch multiple instance of mopidy on one snapcast server.

How to affect a specific soundcard on one mobidy instance ? 
Is it the correct way to do ? Also, in this type of configuration , will I have the ability to do a multiroom and also, a specific room stream ?

I guess I need to start multiple snapclient instances but I'm a bit lost to do that, and to affect them on a specific DAC)

THank you !

Bertrand

**Comment by mariolukas** [comment]
Hi Bertrand,

> * I would like, if possible, to stream directly from my phone Spotify App

Not directly. You will need an additional configuration on the snapcast part of hydraplay. But why would you stream directly from your spotify phone app. You can use hydraplays spotify integration.

> * ...And if possible use only one Raspberry with multiple soundcards
> * Also, if possible, have Airplay

Depends on the sound card, USB soundcard or  soundcard attached as a HAT. I don't know if there any soundcard exists in form of a HAT which is stackable. But i think it is also possible to use a soundcard with multiple output channels.

> Of what I understood, Hydraplay will launch multiple instance of mopidy on one snapcast server.
> 
> How to affect a specific soundcard on one mopidy instance ? Is it the correct way to do ? Also, in this type of configuration , will I have the ability to do a multiroom and also, a specific room stream ?

You are right, Hydraplay acts as a server. Wich combines Snapcast server + x Mopidy instances. Each Mopidy instance can be compared so a streaming source ( with the capability to provide an audio stream form spotify, youtube, tunein, ... you name it depending on the installed mopidy extension). The server does not need a soundcard. 

Furthermore you will need Snapcast Clients running. Each client represents a zone/room/speaker. A client can be represented by another pi with soudcard, a browser using snapcast web client or even the snapcast android app. 

Each client connects to the server and appears as a Player in the HydraPlay UI. HydraPlay allows you to control those clients by grouping clients or switching between streams (Mopidy). 

> 
> I guess I need to start multiple snapclient instances but I'm a bit lost to do that, and to affect them on a specific DAC)

That's correct. But it is not rocket science. Start wit a single client. e.g. Raspberry pi with one of those cheap audio HAT ( ~20 €). Install plain Raspberry Pi OS (lite) and the driver for the audio HAT (e.g. https://www.waveshare.com/wm8960-audio-hat.htm, Installation instructions: https://www.waveshare.com/wiki/WM8960_Audio_HAT). Add the hydraplay server ip to the snapcast client config. That's it. The Client will appear in HydraPlay's ui.

> THank you !
> 
> Bertrand

But in case you just want to try the whole setup. I would suggest to use the HydraPlay docker image, see https://github.com/mariolukas/HydraPlay#getting-started You can install it on any hardware which supports docker. Then just use the client web ui in a browser and you will get the idea behind HydraPlay.

You are welcome,
- Mario

**Comment by beber666** [comment]
Thank you for your reply :-)
For the Snapcast multi client, someone did that on Reddit , with a Orange PI Zero 

I guess this will be a great feature if you add some documentation to do that. 

Because it will make Hydray play a perfect choice for easy multiroom setup

What do you think ? 
Anyway, I know this is time consuming, it's just an advice from a noob user.

If you can, I will just need some advices to launch multi snapcast client sessions

Thanks again
