### ISSUE TITLE
Spotify controls via Spotify Connect API

### ISSUE THREAD

**Issue by LeoSum8** [mariolukas/HydraPlay#8]
Hi @mariolukas 
in my setup I use snapcast with one mpd and one spotify (via librespot) stream. I guess the mopidy controller you have in place would also be able to control mpd. If not, switching to mopidy would not be an issue for me.

What would be required to add support for librespot control via this interface?
I guess you would only need to issue different play/pause/next/previous commands for a new stream type, am I correct?
In a quick search I found a few implementations for the Spotify Connect API in the programming languages you use here which is used to issue these commands:
JavaScript: https://github.com/thorpelawrence/alexa-spotify-connect/blob/master/connect.js#L109
TypeScript: https://github.com/illBeRoy/spotify-tvos-app/blob/9abd14ab8948a8dd8bc431440b00363e44bd932a/src/api/spotify.driver.ts#L44

Is this something you might look into or is this out of your scope here?

**Comment by mariolukas** [comment]
There are different services. One for to speak with the snapcast api (stream control, volume control, client control, groups etc.). The other one is for controlling mopidy ( start/stop, select source/stream, etc.).
I heard of librespot, but i hadn't  a closer look to it until now. Maybe it is possible to integrate it. At the moment the services and UI are build to control mopidy. I am using [mopidy-spotify](https://github.com/mopidy/mopidy-spotify) for spotify integration. 

If there is a simple way to integrate it there would be a scope. Hopefully there will be some contributions to the project in the near future.

**Comment by mariolukas** [comment]
Just added a diagram to Readme.md how things are hooked up together.

**Comment by mariolukas** [comment]
The new version adds Spotify support by mopidy spotify extension.
