### ISSUE TITLE
Exposed constainer ports

### ISSUE THREAD

**Issue by ClasSicKilian** [mariolukas/HydraPlay#81]
`EXPOSE 32768-61000`

Are these ports really all necessary?
I use Unraid with a custom network and all exposed ports are displayed in a list, the interface takes a long time to load because the list is too long.

It's a great project, thanks a lot for that.

**Comment by mariolukas** [comment]
Hi, 

> Are these ports really all necessary?
> I use Unraid with a custom network and all exposed ports are displayed in a list, the interface takes a long time to load because the list is too long.
> 

only the following ports are needed 

      - 8080:8080 (web)
      - 1780:1780 (snapcast)
      - 1704:1704 (snapcast)
      - 1705:1705 (snapcast)
      
      - 6680-6690:6680-6690 ( port range for mopidy instances, in this case you are able to use up to 10 mopidies as stream)

I will fix that in the docker file within the next release. 

> It's a great project, thanks a lot for that.

    Thanks.
