### ISSUE TITLE
hydraplay server not fully loading + snapserver error

### ISSUE THREAD

**Issue by Sungod3000** [mariolukas/HydraPlay#87]
Hi, 

im installing hydraplay on an RPi3+ and im almost there. 

I had some issues with docker not pulling an arm64bit version of hydraplay so I installed a 32bit raspian and now the docker gets correctly launched.

I can acces the landingpage of mopidy correctly and hydraplay does load, but it only show a grey background and a red "A" as favicon. 
Also im not reaching snapcast. On 0.0.0.0:1780 I get "The resource '/' was not found." and the the client under port 1704 times out.

Could it be that the snapserver is not running and therefore hydraplay cant fully run as well?

anyay keep up the good work. 
Cheers
F.

**Comment by mariolukas** [comment]
Can you provide the corresponding log lines?

**Comment by jreusch** [comment]
hey hey
i had a simmilar issue when just renaming the example config to hydra.private.json

the output of docker-compose up gave it away that snapserver cannot find /tmp/additional_streams.
so either removing those from the config or adding in docker-compose.yml
```
- /tmp/hydra-snapserver/:/tmp/additional_stream
```
under the volumes section helped that it could successfully startup.

@mariolukas  maybe adding a comment/example volume map in docker-compose.yml or inside the example hydra config would help? what would be your preference i could create an PR.

**Comment by mariolukas** [comment]
> @mariolukas maybe adding a comment/example volume map in docker-compose.yml or inside the example hydra config would help? what would be your preference i could create an PR.

PR would be great.
