### ISSUE TITLE
Exception compile player without docker

### ISSUE THREAD

**Issue by Medel** [mariolukas/HydraPlay#99]
If I try "ng build" there is an error.

> An unhandled exception occurred: Cannot find module './util'
Require stack:
- /usr/local/src/HydraPlay/src/ui/node_modules/webpack-subresource-integrity/plugin.js
- /usr/local/src/HydraPlay/src/ui/node_modules/webpack-subresource-integrity/index.js
- /usr/local/src/HydraPlay/src/ui/node_modules/@angular-devkit/build-angular/src/webpack/configs/common.js
- /usr/local/src/HydraPlay/src/ui/node_modules/@angular-devkit/build-angular/src/webpack/configs/index.js
- /usr/local/src/HydraPlay/src/ui/node_modules/@angular-devkit/build-angular/src/builders/browser/index.js
- /usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
- /usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/src/command-builder/architect-base-command-module.js
- /usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/src/command-builder/architect-command-module.js
- /usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/src/commands/build/cli.js
- /usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/src/command-builder/command-runner.js
- /usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/lib/init.js
See "/tmp/ng-T6MtxC/angular-errors.log" for further details.
/usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

Error: Cannot find module './util'
Require stack:
- /usr/local/src/HydraPlay/src/ui/node_modules/webpack-subresource-integrity/plugin.js
- /usr/local/src/HydraPlay/src/ui/node_modules/webpack-subresource-integrity/index.js
- /usr/local/src/HydraPlay/src/ui/node_modules/@angular-devkit/build-angular/src/webpack/configs/common.js
- /usr/local/src/HydraPlay/src/ui/node_modules/@angular-devkit/build-angular/src/webpack/configs/index.js
- /usr/local/src/HydraPlay/src/ui/node_modules/@angular-devkit/build-angular/src/builders/browser/index.js
- /usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
- /usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/src/command-builder/architect-base-command-module.js
- /usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/src/command-builder/architect-command-module.js
- /usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/src/commands/build/cli.js
- /usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/src/command-builder/command-runner.js
- /usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/lib/init.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/usr/local/src/HydraPlay/src/ui/node_modules/webpack-subresource-integrity/plugin.js:32:16)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/src/HydraPlay/src/ui/node_modules/webpack-subresource-integrity/plugin.js',
    '/usr/local/src/HydraPlay/src/ui/node_modules/webpack-subresource-integrity/index.js',
    '/usr/local/src/HydraPlay/src/ui/node_modules/@angular-devkit/build-angular/src/webpack/configs/common.js',
    '/usr/local/src/HydraPlay/src/ui/node_modules/@angular-devkit/build-angular/src/webpack/configs/index.js',
    '/usr/local/src/HydraPlay/src/ui/node_modules/@angular-devkit/build-angular/src/builders/browser/index.js',
    '/usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js',
    '/usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js',
    '/usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/src/command-builder/architect-base-command-module.js',
    '/usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/src/command-builder/architect-command-module.js',
    '/usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/src/commands/build/cli.js',
    '/usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/src/command-builder/command-runner.js',
    '/usr/local/src/HydraPlay/src/ui/node_modules/@angular/cli/lib/cli/index.js',
    '/usr/local/lib/node_modules/@angular/cli/lib/init.js'
  ]
}

Node.js v18.12.1

**Comment by mariolukas** [comment]
Hi, 

the project ist using Angular 14. But Angular 14 does not work with Node.js 18.x.x
see: https://github.com/angular/angular/issues/45870#issuecomment-1118696409

- Mario

**Comment by Medel** [comment]
I have tried several node versions on a Raspberry. Some of them crash with "npm install" at "esbuild...". Which Version is the best? 
Raspberry Pi 3 Model B Rev 1.2
Raspbian GNU/Linux 11 (bullseye)

**Comment by Medel** [comment]
After many tries I could install Node v16.13 on my Raspberry 3
I have to close all services that I not need for install.
But after "ng build" there were two errors "allocation failure scavenge might not succeed".
`node -e 'console.log(v8.getHeapStatistics().heap_size_limit/(1024*1024))'`
shows me 236 Memory
I set the memory to 400 with:
`export NODE_OPTIONS="--max-old-space-size=400"`
After that it compiles successfully.
